# 1. print("\tResume:\nName:Hesen\tAge:13\tHobby:Programing")

# 2.
# print("           ---                                                                                                                                                                                   ")
# print("          /   \                                                                                                                                                               ")
# print("         /     \                                                                                                                                                               ")
# print("         |     |                                                                                                                                                               ")
# print("         |     |                                                                                                                                                              ")
# print("         |     |                                                                                                                                                               ")
# print("         \     /                                                                                                                                                            ")
# print("          \   /                                                                                                                                                             ")
# print("           ---                                                                                                                                                                 ")

# 3. print("\"To be\n\tor not \n\t\t to be!\"\n\t\t\t/Shakespeare/")

# 4. print("\t\t Escape sequences\n\\a    Bell (alert)\n\\b    Backspace\n\\n    New line\n\\r    Carriage return\n\\t    Horizontal tab\n\\\\    Backslash \\\n\\\"    Double quotation mark \"\n\\\'    Single quotation mark \'  ")
      
# 5.    
# print("     *             *            ****              ********                  ****              *            *                                                                                 ")
# print("     *             *           *    *           ***                        *    *             * *          *                                                                                 ")
# print("     *             *          *      *        ***                         *      *            *   *        *                                                                                 ")
# print("     *             *         *        *      **                          *        *           *    *       *                                                                                 ")
# print("     *             *        *          *     *                          *          *          *     *      *                                                                                 ")
# print("     ***************       **************     ***                      **************         *      *     *                                                                                 ")
# print("     *             *      *              *         ****               *              *        *       *    *                                                                                 ")
# print("     *             *     *                *             ***          *                *       *        *   *                                                                                 ")
# print("     *             *    *                  *               **       *                  *      *         *  *                                                                                 ")
# print("     *             *   *                    *            ***       *                    *     *          * *                                                                                 ")
# print("     *             *  *                      *   *********        *                      *    *            *                                                                                 ")

# 6. print("\"   \'\\t\' , \"   \'\\n\' , \"   \'\\\\\',\"   \'\\\'\", \"   \'\\\"\', \"")
# 7. print("                                                                                                                         ")
# print("        ********************                                                                                                   ")
# print("       *|                 **                                                                                                   ")
# print("      * |                * *                                                                                                   ")
# print("     *  |               *  *                                                                                                   ")
# print("    *   |              *   *                                                                                                   ")
# print("   *    |             *    *                                                                                                   ")
# print("  *     |            *     *                                                                                                   ")
# print(" ********************      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |           *      *                                                                                                   ")
# print(" *      |__________________*                                                                                                   ")
# print(" *     /            *     *                                                                                                    ")
# print(" *    /             *    *                                                                                                     ")
# print(" *   /              *   *                                                                                                      ")
# print(" *  /               *  *                                                                                                       ")
# print(" * /                * *                                                                                                        ")
# print(" */                 **                                                                                                         ")
# print(" ********************                                                                                                          ")

